In [2]:
import torch
print(torch.__version__)

2.14.0


Introcudtion to tensors : 
Tensor is the fundemental building block of machine learning 
represents data in a numberical way

In [3]:
#Creating tensors
#first thing to create is a SCALAR
#scalar is a zero dimension tensor

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#torch.Tensor is a python integer
#get the number withtin the Tensor , can use item() method but only works with one element tensors

scalar.item()

7

In [6]:
#Vector
#single dimension tensor but contains many numbers
vector = torch.Tensor([7,7])
vector

tensor([7., 7.])

As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

In [7]:
#cheking how many dimensions does it have
vector.ndim

1

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

In [8]:
#tensor' s shape attribute
vector.shape

torch.Size([2])

In [10]:
#means the vector has a shape of [2]

#theres matrices
MATRIX = torch.Tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7.,  8.],
        [ 9., 10.]])

In [12]:
MATRIX.ndim #counts the number of brackets

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
#how to create a tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

**Tensor Initialization**

 With 60 mins blitz from official pytorch site

In [23]:
#can be initialised in different ways _ this here is direclty from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [26]:
import numpy as np
#From a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [27]:
#from another tensor  
x_ones = torch.ones_like(x_data) #retains the properties of the initial tensor
print(f'Ones tensor :{x_ones}')

Ones tensor :tensor([[1, 1],
        [1, 1]])


In [29]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f'Random tensor {x_rand}')

#overrides the datatype of x_data but keeps the same dimensions 
#the data differs - now float

Random tensor tensor([[0.5558, 0.3552],
        [0.0523, 0.5080]])


In [30]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [31]:
rand_tensor

tensor([[0.1874, 0.4862, 0.0250],
        [0.0222, 0.3782, 0.2796]])

In [32]:
ones_tensor


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [33]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])