In [2]:
import torch
print(torch.__version__)

2.14.0


Introcudtion to tensors : 
Tensor is the fundemental building block of machine learning 
represents data in a numberical way

In [3]:
#Creating tensors
#first thing to create is a SCALAR
#scalar is a zero dimension tensor

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#torch.Tensor is a python integer
#get the number withtin the Tensor , can use item() method but only works with one element tensors

scalar.item()

7

In [6]:
#Vector
#single dimension tensor but contains many numbers
vector = torch.Tensor([7,7])
vector

tensor([7., 7.])

As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.

In [7]:
#cheking how many dimensions does it have
vector.ndim

1

You can tell the number of dimensions a tensor in PyTorch has by the number of square brackets on the outside ([) and you only need to count one side.

In [8]:
#tensor' s shape attribute
vector.shape

torch.Size([2])

In [10]:
#means the vector has a shape of [2]

#theres matrices
MATRIX = torch.Tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7.,  8.],
        [ 9., 10.]])

In [12]:
MATRIX.ndim #counts the number of brackets

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
#how to create a tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])